INIDAN_STATE_CODES = {
    "AN": "Andaman and Nicobar",
    "AP": "Andhra Pradesh",
    "AR": "Arunachal Pradesh",
    "AS": "Assam",
    "BR": "Bihar",
    "CH": "Chandigarh",
    "DN": "Dadra and Nagar Haveli",
    "DD": "Daman and Diu",
    "DL": "Delhi",
    "GA": "Goa",
    "GJ": "Gujarat",
    "HR": "Haryana",
    "HP": "Himachal Pradesh",
    "JK": "Jammu and Kashmir",
    "KA": "Karnataka",
    "KL": "Kerala",
    "LD": "Lakshadweep",
    "MP": "Madhya Pradesh",
    "MH": "Maharashtra",
    "MN": "Manipur",
    "ML": "Meghalaya",
    "MZ": "Mizoram",
    "NL": "Nagaland",
    "OD": "Odissa",
    "PY": "Pondicherry",
    "PN": "Punjab",
    "RJ": "Rajasthan",
    "SK": "Sikkim",
    "TN": "TamilNadu",
    "TR": "Tripura",
    "UP": "Uttar Pradesh",
    "WB": "West Bengal",
    "CG": "Chhattisgarh",
    "TS": "Telangana",
    "JH": "Jharkhand",
    "UK": "Uttarakhand"
}
